#Default port is 8090
server:
  port: 8090
  
info:
  app:
    name: Dog Service local
 
endpoints:
    enabled: false
    info.enabled: true
    health.enabled: true
    metrics.enabled: true
  
management:
  security:
    enabled: false
      
opentracing:
  jaeger:
    log-spans: false
    const-sampler:
      decision: true
    probabilistic-sampler:
      sampling-rate: 1.0
    enable-b3-propagation: true      
      
security:
  oauth2:
   resource:
      userInfoUri: http://localhost:8095/auth/user

#Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.scc: DEBUG
