#Default port is 8090
server:
  port: 8090
  
security:
  oauth2:
   resource:
      userInfoUri: http://authentication-service:8095/auth/user
        
#Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.scc: DEBUG
