#Default port is 8090
server:
  port: 8090
  
info:
  app:
    name: Dog Service
  
endpoints:
    enabled: false
    info.enabled: true
    health.enabled: true
    metrics.enabled: true
  
management:
  security:
    enabled: false
      
security:
  oauth2:
   resource:
      userInfoUri: http://authentication-service:8095/auth/user

spring:
  zipkin:
    base-url: http://${ZIPKIN_SERVICE_HOST}:${ZIPKIN_SERVICE_PORT}
        
#Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.scc: DEBUG
